name: packer

on:
  push:

env:
  PRODUCT_VERSION: "1.10.0"

jobs:
  packer:
    runs-on: ubuntu-22.04
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "ls -l ; git status ; git log ; packer init ."

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."

      - name: Run `make`
        id: make
        run: "make"
